<?php
namespace Www\Facades;

use Illuminate\Support\Facades\Facade;

class PackageTest extends Facade
{
    protected static function getFacadeAccessor()
    {
        // TODO: Change the autogenerated stub
        return "packagetest";
    }

}
